/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddBalanceDialog: typeof import('./src/components/AddBalanceDialog.vue')['default']
    BalanceItem: typeof import('./src/components/BalanceItem.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Home: typeof import('./src/pages/Home.vue')['default']
    Login: typeof import('./src/pages/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
